name: B-FAST Deployment

on:
  push:
    tags:
      - 'v*' # Dispara quando você cria uma tag como v1.0.0

permissions:
  contents: read

jobs:
  # JOB 1: Compila os binários Rust para Python (Linux, Windows, Mac)
  build_python_wheels:
    name: Build Python Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    permissions:
      id-token: write
      attestations: write
      contents: read

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.10'

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install maturin
        run: pip install maturin

      - name: Build wheels
        run: maturin build --release --out dist --find-interpreter

      - name: Generate build provenance attestations
        uses: actions/attest-build-provenance@ef244123eb79f2f7a7e75d99086184180e6d0018 # v1
        with:
          subject-path: 'dist/*'

      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist

  # JOB 2: Publica no PyPI (Python)
  publish_python:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build_python_wheels]
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          pattern: wheels-*
          merge-multiple: true
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  # JOB 3: Compila e Publica no NPM (TypeScript)
  publish_typescript:
    name: Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install and Build TS Client
        run: |
          cd client-ts
          npm install
          npm run build
        
      - name: Publish to NPM
        run: |
          cd client-ts
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}